theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: 
27 ans 
ğŸ“Š Data wizard 
ğŸ¤– Machine learning
ğŸ’» Software developer
ğŸ”¢ Statistics
ğŸ§ª Biology
ğŸ§¬ Next generation sequencing 
ğŸ’¡ Proactive & Forward-thinking
ğŸƒâ€â™‚ï¸ Sport-lover
ğŸ» Team-building
