theme: jekyll-theme-minimal
title: ğŸ’»âœ’ï¸ğŸ“„ğŸŒŸ
description: 27 ans <br>ğŸ’» Software developer<br>ğŸ“Š Data wizard<br>ğŸ¤– Machine learning<br>ğŸ”¢ Statistics<br>ğŸ§ª Biology<br>ğŸ§¬ Next generation sequencing<br>ğŸ’¡Proactive & Forward-thinking<br>ğŸƒâ€â™‚ï¸ Sport-lover<br>ğŸ» Team-building
