theme: jekyll-theme-minimal
title: Arnaud DUVERMY
description: | 
  27 years old <br>
  ğŸ’» Software developer<br>
  ğŸ“Š Data wizard<br>
  ğŸ¤– Machine learning<br>
  ğŸ”¢ Statistics<br>
  ğŸ§ª Biology<br>
  ğŸ§¬ Next generation sequencing<br>
  ğŸ’¡Proactive & Forward-thinking<br>
  ğŸƒâ€â™‚ï¸ Sport-lover<br>
  ğŸ» Team-building<br><br><br>
  <a href="https://fr.linkedin.com/in/arnaud-duvermy-b49248132"><img src="additional-content/logo-linkedin.svg"  width="30" height="30"></a> 
  <a href="https://github.com/aduvermy/"><img src="additional-content/github-logo.svg"  width="30" height="30"></a>
  <a href="https://aduvermy.github.io/digital-cv/"><img src="additional-content/logo-www.png"  width="30" height="30"></a>

