theme: jekyll-theme-minimal
title: Arnaud DUVERMY
logo: "./additional-content/logo-pic.png"
description: | 
  <center>
  Software developer & Data Scientist in Biology <br><br>
  </center>  
  ğŸ’» Software developer<br>
  ğŸ“Š Data wizard<br>
  ğŸ¤– Machine learning<br>
  ğŸ”¢ Statistics<br>
  ğŸ§ª Biology<br>
  ğŸ§¬ Next generation sequencing<br>
  ğŸ’¡Proactive & Forward-thinking<br>
  ğŸƒâ€â™‚ï¸ Sport-lover<br>
  ğŸ» Team-building<br><br>
  <a href="https://fr.linkedin.com/in/arnaud-duvermy-b49248132"><img src="additional-content/logo-linkedin.svg"  width="35" height="35"></a> 
  <a href="https://github.com/aduvermy/"><img src="additional-content/github-logo.svg"  width="35" height="35"></a>
  <a href="https://aduvermy.github.io/digital-cv/"><img src="additional-content/logo-www.png"  width="35" height="35"></a>
  <a href="https://www.canva.com/design/DAEsiZY7szc/b3WlWb3fqFCH2BPImJL3Yw/edit?utm_content=DAEsiZY7szc&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton"><img src="additional-content/resume.png"  width="35" height="35"></a>

